#!/bin/bash

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /data/models/Vicuna-7b \
    --version v1 \
    --data_path /data/LLaVA-Finetuning/llava_v1_5_mix665k/llava_v1_5_mix665k.json \
    --image_folder /data/LLaVA-Finetuning/llava_v1_5_mix665k \
    --vision_tower /data/models/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /data/VisualPrism/checkpoints/llava-visualprism-7b-pretrain/mm_projector.bin \
    --mm_projector_type visualprism \
    --scale_factor 2 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /data/VisualPrism/checkpoints/llava-visualprism-7b \
    --no_use_sinkhorn_lsd \
    --sinkhorn_alpha_ce 1.0 \
    --sinkhorn_beta 0.2 \
    --sinkhorn_tau_sd 2.0 \
    --sinkhorn_lambda 0.1 \
    --sinkhorn_iters 20 \
    --sinkhorn_max_tokens 768 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to "none"

